[context.nixos]
includes = ["**/*.nix"]
stubs = ["@nixos"]

[stubs.generate]
nixpkgs = { expr = "(builtins.getFlake (toString ./.)).inputs.nixpkgs" }
nixvim = { expr = "(builtins.getFlake (toString ./.)).inputs.nixvim" }

[project]
includes = ["**/*.nix"]
excludes = ["result", ".direnv"]
